fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h

Fixes #7
Submitted by @skliper , CLA on file
Testing:
- make ENABLE_UNIT_TESTS=TRUE SIMULATION=native prep
- Built on linux with -DCFE_OMIT_DEPRECATED_6_6 with no build errors
- make test passed (except osal_timer_UT which occasionally fails on linux)
- cFS executes and loads apps with no issues

Replace deprecated cfe refs, #7

---

.travis.yml

Fix #24 - CI enforcement of style
See CI results - no independent testing required
Style enforced, CI will fail if new pull request does not meet expected style.
**System(s) tested on:**
- CI, requires https://github.com/nasa/cFS/pull/38 to be merged to master to work
None
**Contributor Info**
Jacob Hagement - NASA/GSFC

Fix #24, Enforce standard style in CI

---

.travis.yml

Fix #39 
Ran CI
CI builds
No more warnings in config section of travis
CI - Ubuntu Bionic
Gerardo E. Cruz-Ortiz NASA/GSFC

Fix #39, Clang-format-10 fails in Travis CI

---

fsw/src/ci_lab_msg.h

Minor fixup for comments in recent merge
The recent name fixes created two occurrences of `CI_LAB_Lab` inside commends which was not noticed during review.  Minor fix.
Sanity check only - Build and run, confirm no issues.
None - fixes code comment issue only.
- Ubuntu 18.04 LTS, 64 bit

Fix comment issues in recent ic-20200304 merge

---

fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h

Avoid port conflicts when having more than one CPU within the same mission load CI_LAB app.  Instead of binding to the port directly, add the CPU number as an offset.  Subtract 1 so that CPU1 remains at the same port (1234 by default) and cmdUtil is not affected.
NOTE: the "cpu number" can be overridden on the command line when using the pc-linux PSP, thereby also permitting the listen point to be tuned for each launch config, if necessary.
Build using default config, ensure no errors.
Run FSW and test sending commands with `cmdUtil` - confirm no impact when using defaults, still listens on port 1234 as before and can send commands.
Run FSW using `--cpuid 2` switch, confirm that listening port has changed, observing syslog trace: …

Fix #37, Offset the UDP base port per-CPU

---

fsw/src/ci_lab_app.c

Apply the `CFE_SB_MsgIdToValue()` and `CFE_SB_ValueToMsgId()` routines where compatibility with an integer MsgId is necessary - syslog prints, events, compile-time MID `#define` values.
Fixes #45 
Unit test
Execute CFE and sanity-check normal operation - send commands to app using `cmdUtil` and confirm commands are processed normally.
No impact to behavior.
Ubuntu 18.04 LTS, 64-bit
In future versions of CFE SB the MsgId type might not be a simple integer, so this is one step in the direction of avoiding this assumption in apps.

Fix #45, Opaque CFE_SB_MsgId_t values

---

fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h

Replace references to `ccsds.h` types with the `cfe_sb.h`-provided type. 
Fixes #48
Build and sanity check CFE, run all unit tests
No impact to behavior
Ubuntu 20.04

Fix #48, remove references to CCSDS types

---

README.md
fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h
fsw/src/ci_lab_version.h

Fix #48
https://github.com/nasa/cFS/pull/96/checks
PR #49 - Replace references to `ccsds.h` types with the `cfe_sb.h`-provided type. 
Ubuntu:Bionic
Part of nasa/cFS#96
None

Integration Candidate: 2020-05-27

---

README.md
fsw/src/ci_lab_app.c
fsw/src/ci_lab_version.h

Close #51 
Bundle test - https://github.com/astrogeco/cFS/runs/972139876
Version reporting uses version string macro and reports development versions build number. Development version display shows up as
```
EVS Port1 42/1/CI_LAB_APP 3: CI Lab Initialized. CI Lab App DEVELOPMENT BUILD v2.3.0+dev36, Last Official Release: v2.3.0
```
Augmented [GCC Docker Image](https://github.com/docker-library/gcc/blob/36c1ff6d7b44428b35fa8b61787c76b225d8184a/10/Dockerfile)
None
None
Gerardo E. Cruz-Ortiz, NASA-GSFC

Close #51, Add buildnumber and baseline

---

fsw/src/ci_lab_app.c

Update the SocketID field to be `osal_id_t` instead of `uint32`
Fixes #54 
Build and sanity test CFE
None.
Ubuntu 20.04
This makes it consistent with other modules

Fix #54, Update CI_Lab to use osal_id_t

---

README.md
fsw/src/ci_lab_app.c
fsw/src/ci_lab_version.h

Fix #54 
See Bundle PR - https://github.com/nasa/cFS/pull/147/checks
PR #55 -  Update the SocketID field to be `osal_id_t` instead of uint32
Ubuntu CI
Part of <https://github.com/nasa/cFS/pull/147>
None
@jphickey

Integration candidate 2020-10-13

---

fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h
fsw/src/ci_lab_msg.h

Replaces deprecated SB API's with MSG
Fix #57
Built and ran, enabled telemetry, checked noops
None
- Hardware: cFS Dev Server
- OS: Ubuntu 18.04
- Versions: Bundle main + this commit
nasa/cFE#777
None
Jacob Hageman - NASA/GSFC

Fix #57, Use MSG APIs

---

fsw/src/ci_lab_msg.h

Fix #59 - removes OS_PACK (not portable)
Didn't confirm offsets, but checked size before and after and there was no change (36).  cFS-GroundSystem doesn't display the message, but passed unit tests and ran a few commands through the system.
No impact, but removes undesirable pattern
- Hardware: cFS Dev Server
- OS: Ubuntu 18.04
- Versions: Bundle main + this commit
Will update other patterns to match #1009 in a separate commit/PR.
None
Jacob Hageman - NASA/GSFC

Fix #59, Remove non-portable OS_PACK

---

README.md
fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h
fsw/src/ci_lab_msg.h
fsw/src/ci_lab_version.h

Fix #57, Use MSG APIs
Fix #59, Remove non-portable OS_PACK
Bundle CI on astrogeco: https://travis-ci.com/github/astrogeco/cFS/builds/200387877
PR #58 -  Replaces deprecated SB API's with MSG
PR #61 - No behavior impact, removes undesirable pattern use of `OS_PACK`
Ubuntu CI
Part of https://github.com/nasa/cFS/pull/156
None
@skliper

Integration Candidate 2020-11-10

---

fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h
fsw/src/ci_lab_msg.h

Fix #62 (updates related to nasa/cFE#1009, implementing a consistent message alignment pattern)
- Use CFE_SB_Buffer_t for receiving and casting to command types
- Use CFE_MSG_CommandHeader_t and CFE_MSG_TelemetryHeader_t in
comamnd and telemetry type definitions
- Use CFE_SB_TransmitMsg_t to copy the command and telemetry
into a CFE_SB_Buffer_t and send it where needed
- Avoids need to create send buffers within the app (or union
the packet types with CFE_SB_Buffer_t)
- Eliminates references to CFE_SB_CmdHdr_t and CFE_SB_TlmHdr_t
that formerly enforced alignment since these had potential
to change the actual packet sizes
- No need to cast to CFE_MSG_Message_t anywhere since it's
available in the CFE_SB_Buffer_t union
Normal build, tested …

Fix #62, Apply message alignment pattern

---

README.md
fsw/src/ci_lab_app.c
fsw/src/ci_lab_app.h
fsw/src/ci_lab_msg.h
fsw/src/ci_lab_version.h

Fix #62, Apply message alignment pattern 
See <https://github.com/nasa/cFS/pull/160/checks>
PR #63 - Aligns messages according to changes in cFE <https://github.com/nasa/cFE/issues/1009>. Uses the "raw" message cmd/tlm types in definition
Ubuntu 18.04
Part of <https://github.com/nasa/cFS/pull/160>
None
@skliper

ci_lab Integration Candidate: 2020-12-08

---

SECURITY.md

Fix #66 
Created a draft of a security policy markdown file for ci_lab. The purpose of a security policy is to inform users on how to submit bugs or vulnerabilities. It is ideal to include a section for supported versions.
Optional sections that may be included:
- What to expect security-wise such as what type of testing is done
- Address privacy concerns
- Supported versions
- License
- Known vulnerabilities
References to Public Security Policies:
https://github.com/thanos-io/thanos/security/policy
https://github.com/minhealthnz/nzcovidtracer-app/security/policy
https://github.com/odoo/odoo/security/policy
Ariel Adams, ASRC Federal

Fix #66, Create Security Policy

---

.github/workflows/codeql-build.yml

Fix #71 - adds CodeQL analysis
Differences from bundle - path theoretically limited to ci_lab, has timeout, and "security and quality", and only does the build (run not necessary for codeql analysis)
Ran on fork
Adds Code QL analysis on push to main and pull requests (to main)
CI
None
None
Jacob Hageman - NASA/GSFC

Fix #71, Add CodeQL analysis to workflow

---

README.md
SECURITY.md
fsw/src/ci_lab_version.h

PR #75
https://github.com/nasa/cFS/pull/214/checks
None
CI
NA
None
@ArielSAdamsNASA

ci_lab Integration candidate: 2021-03-05

---

SECURITY.md

Fix #74
Updated the Security Policy to include the type of testing done for ci_lab or the cFS bundle under a new section titled "Testing". Provided a disclaimer that under the Apache license, liability is not provided. 
Added that security reports should be emailed. 
Users should now be aware of the type of testing ci_lab or the cFS bundle undergoes. 
References: 
https://github.com/thanos-io/thanos/security/policy
https://github.com/phpMussel/phpMussel/security/policy
https://github.com/timberio/vector/security/policy
Ariel Adams, ASRC Federal

Fix #74, Add Testing Tools to the Security Policy

---

fsw/src/ci_lab_app.h

Use `cfe.h` in ci_lab rather than the individual component-specific headers.
The all-inclusive header should give everything needed, and be more future proof in case component names ever need to change.
Fixes #77 
Build and sanity check CFE
No impact
Ubuntu 20.04
Needed for nasa/cfe#1203

Fix #77, use cfe.h instead of individual headers

---

CONTRIBUTING.md

Fix #80
Added a contributing guide that links to the main cFS contributing guide. 
Users should be able to view the contributing guide contents easily from the ci_lab repo. 
Ariel Adams, ASRC Federal

Fix #80, Add Contributing Guide

---

fsw/src/ci_lab_app.c
fsw/src/ci_lab_events.h

Updates CI_LAB to obtain a buffer prior to calling `OS_SocketRecvFrom`, and then transmit that same buffer directly rather than copying it.
This demonstrates use of the Zero Copy API.
Fixes #73
Build CFE along with nasa/cfe#1257 and send various commands using "cmdUtil".  Confirm that commands were received correctly.
Internal change only - No impact to external behavior.
Ubuntu 20.04
Requires nasa/cfe#1257 as prerequisite

Fix #73, use zero copy API

---

fsw/src/ci_lab_app.c
fsw/src/ci_lab_events.h

Fix #82, remove app registration 
Fix #73, use zero copy API 
ci_lab checks <https://github.com/nasa/ci_lab/pull/85/checks>
bundle checks <https://github.com/nasa/cFS/pull/227/checks>
Removes unnecessary call to `CFE_ES_RegisterApp()` since app registration is done automatically.
Demonstrates the use of the Zero Copy API. Adds a step that obtains a buffer prior to calling OS_SocketRecvFrom then transmits that same buffer directly rather than copying it.
Part of <https://github.com/nasa/cFS/pull/227>
None
@jphickey

ci_lab Integration candidate: 2021-03-30

---

.github/workflows/codeql-build.yml

Fix #86 
Added the duplicate jobs action to avoid duplicate jobs from running. Added a separate job for coding standard queries. Created two configuration files, one for default queries and security queries and another for jpl rules. Removed push on main branch so when users push code to their forked repos, the workflow runs. Added main branch to pull request, so CodeQL runs on pull request made in the main branch. This is the same logic used in the cFS bundle repo. 
Testing done on cFE forked repository, ArielSAdamsNASA/cFE which used the same files, but with different configuration paths.
Jobs were failing when the entire path of the configuration file were not used. Have to use nasa/cFE/.github/codeql/config-name@branch-name. The …

Fix #86, Implement Coding Standard Rules in CodeQL

---

SECURITY.md
fsw/src/ci_lab_app.c

Fixed a couple of minor typos in the _text_ of:
- SECURITY.md
...and in the _comments_ of:
- fsw/src/ci_lab_app.c
None (non-executable code).
None (minor Markdown doc and comments changes).
n/a
n/a
**Code contributions**
n/a

Fixed typos in SECURITY.md and ci_lab_app.c

---

fsw/src/ci_lab_app.c

Whenever an integer value is used as a CFE_SB_MsgId_t, it should go through the explicit conversion using the supplied inline
function.
Fixes #91
Build and sanity check CFE
Allows CI_LAB to be built when CFE_SB_MsgId_t is an opaque/non-integer type.
None with default config (where CFE_SB_MsgId_t is an integer type).
Ubuntu

Fix #91, apply CFE_SB_ValueToMsgId where required

---

fsw/src/ci_lab_app.c

- Fix #110
CI
Initializes with an empty filter set (use EVS add filter command to add)
CI
None
None
Jacob Hageman - NASA/GSFC

Fix #110, Remove registration of empty EVS filters
